---
- name: Create node_exporter installation directory
  ansible.builtin.file:
    path: "{{ node_exporter_bin_path }}"
    state: directory
    mode: "0755"
  tags: prometheus, node_exporter

- name: Download and extract node_exporter archive
  ansible.builtin.unarchive:
    src: "{{ node_exporter_package_repo }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  tags: prometheus, node_exporter

- name: Install node_exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ prometheus_architecture_map[ansible_architecture] }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: "restart node_exporter"
  tags: prometheus, node_exporter

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    state: present
  tags: prometheus, node_exporter

- name: Setup systemd service for prometheus-node-exporter
  ansible.builtin.template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service
    mode: 0644
  notify: "restart node_exporter"
  tags: prometheus, node_exporter

- name: Enable and start prometheus-node-exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
  tags: prometheus, node_exporter
