---
# Blue-green upgrade method: inventory example
all:
  vars:
    pg_old_version: 17 # the current (old) version of PostgreSQL
    pg_new_version: 18 # the target version of PostgreSQL for the upgrade
    pg_replication_database: "all" # dbname for replication, 'all' for the entire cluster
  children:
    source_cluster:
      hosts:
        10.128.64.141:
        10.128.64.142:
        10.128.64.143:
    target_cluster:
      hosts:
        10.128.64.151:
        10.128.64.152:
        10.128.64.153:
