---
# Blue-green upgrade method: inventory example
all:
  vars:
    # upgrade settings
    pg_old_version: 17 # the current (old) version of PostgreSQL
    pg_new_version: 18 # the target (new) version of PostgreSQL for the upgrade
    pg_replication_database: "all" # dbname for replication, 'all' for the entire cluster
    # connection settings
    ansible_ssh_user: root
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
  children:
    source_cluster:
      hosts:
        10.128.64.141:
        10.128.64.142:
        10.128.64.143:
    target_cluster:
      hosts:
        10.128.64.151:
        10.128.64.152:
        10.128.64.153:
